-- MySQL Script generated by MySQL Workbench
-- Sat Oct 28 19:35:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema addictionRemoval
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema addictionRemoval
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `addictionRemoval` DEFAULT CHARACTER SET utf8 ;
USE `addictionRemoval` ;

-- -----------------------------------------------------
-- Table `addictionRemoval`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Member` (
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `rating` DOUBLE NULL,
  `accountCreatedOn` DATE NOT NULL,
  `phoneNumber` VARCHAR(15) NULL,
  `city` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `isBanned` TINYINT NULL,
  `isDoc` TINYINT NOT NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Report` (
  `reportid` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Member_email` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`reportid`, `email`),
  UNIQUE INDEX `Report_ID_UNIQUE` (`reportid` ASC),
  UNIQUE INDEX `Type_UNIQUE` (`type` ASC),
  INDEX `fk_Report_Member_idx` (`Member_email` ASC),
  CONSTRAINT `fk_Report_Member`
    FOREIGN KEY (`Member_email`)
    REFERENCES `addictionRemoval`.`Member` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`User` (
  `Member_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Member_email`),
  INDEX `fk_User_Member1_idx` (`Member_email` ASC),
  CONSTRAINT `fk_User_Member1`
    FOREIGN KEY (`Member_email`)
    REFERENCES `addictionRemoval`.`Member` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Addictions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Addictions` (
  `addictionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`addictionName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Case` (
  `isCompleted` TINYINT NULL,
  `caseid` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `severity` VARCHAR(45) NOT NULL,
  `counsellor_email` VARCHAR(45) NOT NULL,
  `patient_email` VARCHAR(45) NOT NULL,
  `startDate` DATE NOT NULL,
  `endDate` DATE NULL,
  `Addictions_addictionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`caseid`),
  UNIQUE INDEX `Caseid_UNIQUE` (`caseid` ASC),
  INDEX `fk_Case_Member1_idx` (`counsellor_email` ASC),
  INDEX `fk_Case_User1_idx` (`patient_email` ASC),
  INDEX `fk_Case_Addictions1_idx` (`Addictions_addictionName` ASC),
  CONSTRAINT `fk_Case_Member1`
    FOREIGN KEY (`counsellor_email`)
    REFERENCES `addictionRemoval`.`Member` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_User1`
    FOREIGN KEY (`patient_email`)
    REFERENCES `addictionRemoval`.`User` (`Member_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Case_Addictions1`
    FOREIGN KEY (`Addictions_addictionName`)
    REFERENCES `addictionRemoval`.`Addictions` (`addictionName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Chats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Chats` (
  `message` LONGTEXT NOT NULL,
  `sentByCounsellor` TINYINT NOT NULL,
  `timestamp` TIMESTAMP(6) NOT NULL,
  `Case_caseid` INT NOT NULL,
  PRIMARY KEY (`Case_caseid`),
  CONSTRAINT `fk_Chats_Case1`
    FOREIGN KEY (`Case_caseid`)
    REFERENCES `addictionRemoval`.`Case` (`caseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Doctor` (
  `Specialization` VARCHAR(45) NOT NULL,
  `Member_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Member_email`),
  CONSTRAINT `fk_Doctor_Member1`
    FOREIGN KEY (`Member_email`)
    REFERENCES `addictionRemoval`.`Member` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Blog` (
  `blogid` INT NOT NULL,
  `message` LONGTEXT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP(6) NULL,
  `Doctor_Member_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`blogid`),
  UNIQUE INDEX `blogid_UNIQUE` (`blogid` ASC),
  INDEX `fk_Blog_Doctor1_idx` (`Doctor_Member_email` ASC),
  CONSTRAINT `fk_Blog_Doctor1`
    FOREIGN KEY (`Doctor_Member_email`)
    REFERENCES `addictionRemoval`.`Doctor` (`Member_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `addictionRemoval`.`Member_had_Addictions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `addictionRemoval`.`Member_had_Addictions` (
  `Member_email` VARCHAR(45) NOT NULL,
  `Addictions_addictionName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Member_email`, `Addictions_addictionName`),
  INDEX `fk_Member_has_Addictions_Addictions1_idx` (`Addictions_addictionName` ASC),
  INDEX `fk_Member_has_Addictions_Member1_idx` (`Member_email` ASC),
  CONSTRAINT `fk_Member_has_Addictions_Member1`
    FOREIGN KEY (`Member_email`)
    REFERENCES `addictionRemoval`.`Member` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Member_has_Addictions_Addictions1`
    FOREIGN KEY (`Addictions_addictionName`)
    REFERENCES `addictionRemoval`.`Addictions` (`addictionName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `addictionRemoval`.`Member`
-- -----------------------------------------------------
START TRANSACTION;
USE `addictionRemoval`;
INSERT INTO `addictionRemoval`.`Member` (`firstname`, `lastname`, `email`, `rating`, `accountCreatedOn`, `phoneNumber`, `city`, `dob`, `isBanned`, `isDoc`) VALUES ('Doc1', 'doc1', 'doc1@gmail.com', 3.5, '2017-10-28', '9565485622', 'Delhi', '1987-12-25', 0, 1);
INSERT INTO `addictionRemoval`.`Member` (`firstname`, `lastname`, `email`, `rating`, `accountCreatedOn`, `phoneNumber`, `city`, `dob`, `isBanned`, `isDoc`) VALUES ('Doc2', 'doc2', 'doc2@gmail.com', 2.5, '2017-10-28', '9565484622', 'Bombay', '1987-08-15', 0, 1);
INSERT INTO `addictionRemoval`.`Member` (`firstname`, `lastname`, `email`, `rating`, `accountCreatedOn`, `phoneNumber`, `city`, `dob`, `isBanned`, `isDoc`) VALUES ('User1', 'user1', 'user1@gmail.com', 2, '2017-10-28', '9545785233', 'Chandigarh', '1985-10-10', 0, 0);
INSERT INTO `addictionRemoval`.`Member` (`firstname`, `lastname`, `email`, `rating`, `accountCreatedOn`, `phoneNumber`, `city`, `dob`, `isBanned`, `isDoc`) VALUES ('User2', 'user2', 'user2@gmail.com', 3, '2017-10-28', '9546765433', 'Kolkata', '1985-09-09', 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `addictionRemoval`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `addictionRemoval`;
INSERT INTO `addictionRemoval`.`User` (`Member_email`) VALUES ('user1@gmail.com');
INSERT INTO `addictionRemoval`.`User` (`Member_email`) VALUES ('user2@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `addictionRemoval`.`Addictions`
-- -----------------------------------------------------
START TRANSACTION;
USE `addictionRemoval`;
INSERT INTO `addictionRemoval`.`Addictions` (`addictionName`) VALUES ('Drinking');
INSERT INTO `addictionRemoval`.`Addictions` (`addictionName`) VALUES ('Drugs');
INSERT INTO `addictionRemoval`.`Addictions` (`addictionName`) VALUES ('Smoking');

COMMIT;


-- -----------------------------------------------------
-- Data for table `addictionRemoval`.`Doctor`
-- -----------------------------------------------------
START TRANSACTION;
USE `addictionRemoval`;
INSERT INTO `addictionRemoval`.`Doctor` (`Specialization`, `Member_email`) VALUES ('Psychologist', 'doc1@gmail.com');
INSERT INTO `addictionRemoval`.`Doctor` (`Specialization`, `Member_email`) VALUES ('Rehabilitation Counselor', 'doc2@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `addictionRemoval`.`Blog`
-- -----------------------------------------------------
START TRANSACTION;
USE `addictionRemoval`;
INSERT INTO `addictionRemoval`.`Blog` (`blogid`, `message`, `title`, `timestamp`, `Doctor_Member_email`) VALUES (1, 'Smoking is bad!', 'This is a blog on smoking', '2017-10-25 13:15:16.000000', 'doc1@gmail.com');
INSERT INTO `addictionRemoval`.`Blog` (`blogid`, `message`, `title`, `timestamp`, `Doctor_Member_email`) VALUES (2, 'Drinking is really bad and harmful.', 'Blog on Drinking', '2017-10-25 13:15:16.000000', 'doc2@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `addictionRemoval`.`Member_had_Addictions`
-- -----------------------------------------------------
START TRANSACTION;
USE `addictionRemoval`;
INSERT INTO `addictionRemoval`.`Member_had_Addictions` (`Member_email`, `Addictions_addictionName`) VALUES ('doc2@gmail.com', 'Drinking');
INSERT INTO `addictionRemoval`.`Member_had_Addictions` (`Member_email`, `Addictions_addictionName`) VALUES ('user2@gmail.com', 'Drinking');
INSERT INTO `addictionRemoval`.`Member_had_Addictions` (`Member_email`, `Addictions_addictionName`) VALUES ('doc1@gmail.com', 'Drugs');
INSERT INTO `addictionRemoval`.`Member_had_Addictions` (`Member_email`, `Addictions_addictionName`) VALUES ('doc2@gmail.com', 'Drugs');
INSERT INTO `addictionRemoval`.`Member_had_Addictions` (`Member_email`, `Addictions_addictionName`) VALUES ('doc1@gmail.com', 'Smoking');
INSERT INTO `addictionRemoval`.`Member_had_Addictions` (`Member_email`, `Addictions_addictionName`) VALUES ('user1@gmail.com', 'Smoking');

COMMIT;
